### ISSUE TITLE
Corrección

### ISSUE THREAD

**Issue by pedroprieto** [organizacion-sesion-3-Juan-Armada/sesion5-travis#1]
Buenas Juan,

Está correcto. Lo único, podrías haber hecho un `fork` de mi repositorio para tener el punto de partida.

Con respecto a los tests, puedes utilizar varias comprobaciones dentro del mismo test. Igual que has puesto este código:
https://github.com/organizacion-sesion-3-Juan-Armada/sesion5-travis/blob/3df14d439c634f294e801d00f0b5a5b184652c01/tests/FuncionesTest.php#L27
puedes poner más aserciones:
```php
$result = $this->funciones->es_par(5); 
$this->assertEquals(false, $result);
$result = $this->funciones->es_par(0); 
$this->assertEquals(true, $result);
```

Buen trabajo!!!

**Comment by juaarbla** [comment]
Perfecto!! lo haré.
No realicé un fork, porque no sabía si querías que lo hiciéramos. Pero lo pensé :-)

**Comment by pedroprieto** [comment]
:+1:
